FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN touch requirements.txt && pip install -r requirements.txt
COPY Practica1.3.py .
RUN chmod +x Practica1.3.py
CMD ["python", "-u", "Practica1.3.py"]